server:
  port: 8081

dubbo:
  application:
    name: pro_kill_bill
  scan:
    base-packages: com.example.dubbobill.service
  registry:
    address: zookeeper://192.168.180.129:2181

mybatis:
  type-aliases-package: com.example.dubbobill.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl

spring:
  shardingsphere:
    props:
      sql:
        show: true
    datasource:
      names: db1,db2,db3
      db1:
        # 配置druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.180.129:3307/pro_kill?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
        username: root
        password: 123456
        #最大连接数
        maxPoolSize: 100
        #最小连接数
        minPoolSize: 5
      db2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.180.129:3308/pro_kill?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
        username: root
        password: 123456
        #最大连接数
        maxPoolSize: 100
        #最小连接数
        minPoolSize: 5
      db3:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.180.129:3309/pro_kill?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
        username: root
        password: 123456
        #最大连接数
        maxPoolSize: 100
        #最小连接数
        minPoolSize: 5
      # 配置数据源的读写分离，但是数据库一定要做主从复制
    masterslave:
      # 配置主从名称，可以任意取名字
      name: ms
      # 配置slave节点的负载均衡均衡策略，采用轮询机制
      load-balance-algorithm-type: round_robin
      # 配置主库master，负责数据的写入
      master-data-source-name: db1
      # 配置从库slave节点
      slave-data-source-names: db2,db3